### ISSUE TITLE
Holding down multiple keys and removing the delay after holding the feed key

### ISSUE THREAD

**Issue by Phoenix132** [LituDev/Cigar3#6]
Hello, this is Phoenix132

I recently considered switching my client to cigar3 and so far it's going pretty well. However, I have encountered some issues in the keys for the client. Here are some issues:

When I press the 'q' key to switch control to minion, the screen blacks out and disconnects.

When I want to perform a solotrick, holding down the feed key and splitting 64x, or 128x, and feeding the majority of mass to a big cell in the front, it doesn't work. I cannot hold multiple keys at a time.

Another issue is a feed delay. I have to hold down the 'w' key to feed, and it only shoots one mass pellet at first, then after a while it continuously feeds.

Thank you for your time if you read all of this.
Please let me know how to fix these issues.

Best,
Phoenix132

Discord: Phoenix3214

**Comment by LituDev** [comment]
Hey,

Thank you for your message.
I will try to fix those issues in the next week :)

Cheers,

Litu

**Comment by Phoenix132** [comment]
Hi, 

Hope the progress is going well.
I tried to fix one of the problems, and I fixed the single feed.

Best,

Phoenix

**Comment by LituDev** [comment]
Hello,

Cigar3 now supports multikey macros. About the Q minion switch issue, i would need the server you're using to reproduce the issue you're having.

Thanks for using Cigar3,

Litu

**Comment by Phoenix132** [comment]
Thank you!

Phoenix
